[package]
publish = false
name = "sengoku-hime-7-text-clean"
version = "0.1.0"
authors = ["Douman <douman@gmx.se>"]

[dependencies]
lazy_static = "*"
regex = "*"
clipboard-win = "*"
clipboard-master = "*"

[lib]
name = "sengoku_hime_7_text_clean"
path = "src/dll.rs"
crate-type = ["dylib"]
